import Foundation
import SwiftUI

struct ExportPrivacyOptions: Hashable {
    var hideExactLocation: Bool = true
    var includeCoachingNotes: Bool = true
}

struct ExportableHoleLine {
    let hole: Int
    let par: Int
    let score: Int
    let putts: Int
}

struct ExportableRoundSummary {
    let courseName: String
    let date: String
    let totalScore: Int
    let relativeToPar: Int
    let totalPutts: Int
    let fairwaysHit: String
    let gir: String
    let penalties: Int
    let holeScores: [ExportableHoleLine]
    let coachingHighlights: [String]
    let locationPrivacyNote: String?
}

struct ExportableClubSummary {
    let clubName: String
    let averageDistance: Int
    let medianDistance: Int
    let sampleSize: Int
    let consistency: String
    let confidence: String
}

struct ExportableStatsSnapshot {
    let playerName: String
    let handicapEstimate: Double
    let roundsPlayed: Int
    let averageScore: Double
    let fairwayPct: Double
    let girPct: Double
    let puttsPerRound: Double
    let bestScore: Int?
    let generatedDate: String
}

enum ExportManager {
    static func roundSummaryText(summary: ExportableRoundSummary) -> String {
        var lines: [String] = []
        lines.append("FairwayIQ — Round Summary")
        lines.append(String(repeating: "=", count: 40))
        lines.append("")
        lines.append("Course: \(summary.courseName)")
        lines.append("Date: \(summary.date)")
        lines.append("Score: \(summary.totalScore) (\(summary.relativeToPar >= 0 ? "+" : "")\(summary.relativeToPar))")
        lines.append("")
        lines.append("Stats")
        lines.append("  Putts: \(summary.totalPutts)")
        lines.append("  Fairways: \(summary.fairwaysHit)")
        lines.append("  GIR: \(summary.gir)")
        lines.append("  Penalties: \(summary.penalties)")
        lines.append("")
        lines.append("Scorecard")
        lines.append("  Hole  Par  Score  Putts")
        for holeScore in summary.holeScores {
            lines.append(String(format: "  %2d    %d    %2d     %d", holeScore.hole, holeScore.par, holeScore.score, holeScore.putts))
        }
        if !summary.coachingHighlights.isEmpty {
            lines.append("")
            lines.append("Coaching Notes")
            for note in summary.coachingHighlights {
                lines.append("  • \(note)")
            }
        }
        if let privacyNote = summary.locationPrivacyNote {
            lines.append("")
            lines.append(privacyNote)
        }
        lines.append("")
        lines.append("Generated by FairwayIQ")
        return lines.joined(separator: "\n")
    }

    static func clubGappingText(clubs: [ExportableClubSummary], playerName: String) -> String {
        var lines: [String] = []
        lines.append("FairwayIQ — Club Gapping Report")
        lines.append(String(repeating: "=", count: 40))
        lines.append("Player: \(playerName)")
        lines.append("")
        lines.append("Club               Avg   Med  Shots  Rating")
        lines.append(String(repeating: "-", count: 55))
        for club in clubs {
            lines.append(
                padded(club.clubName, to: 18) +
                    padded("\(club.averageDistance)yd", to: 6) +
                    padded("\(club.medianDistance)yd", to: 6) +
                    padded("\(club.sampleSize)", to: 7) +
                    club.consistency
            )
        }
        lines.append("")
        lines.append("Generated by FairwayIQ")
        return lines.joined(separator: "\n")
    }

    static func statsSnapshotText(snapshot: ExportableStatsSnapshot) -> String {
        var lines: [String] = []
        lines.append("FairwayIQ — Stats Snapshot")
        lines.append(String(repeating: "=", count: 40))
        lines.append("Player: \(snapshot.playerName)")
        lines.append("Handicap: \(String(format: "%.1f", snapshot.handicapEstimate))")
        lines.append("Rounds: \(snapshot.roundsPlayed)")
        lines.append("Generated: \(snapshot.generatedDate)")
        lines.append("")
        lines.append("Performance")
        lines.append("  Average Score: \(String(format: "%.1f", snapshot.averageScore))")
        lines.append("  Best Score: \(snapshot.bestScore.map(String.init) ?? "—")")
        lines.append("  Fairways: \(String(format: "%.0f%%", snapshot.fairwayPct))")
        lines.append("  GIR: \(String(format: "%.0f%%", snapshot.girPct))")
        lines.append("  Putts/Round: \(String(format: "%.1f", snapshot.puttsPerRound))")
        lines.append("")
        lines.append("Generated by FairwayIQ")
        return lines.joined(separator: "\n")
    }

    static func buildRoundExport(
        round: Round,
        coaching: CoachingSummary?,
        privacy: ExportPrivacyOptions = ExportPrivacyOptions()
    ) -> ExportableRoundSummary {
        let scores = round.holeScores.sorted { $0.holeNumber < $1.holeNumber }
        let holeData: [ExportableHoleLine] = scores.map { score in
            let par = round.course?.holes.first(where: { $0.number == score.holeNumber })?.par ?? 4
            return ExportableHoleLine(hole: score.holeNumber, par: par, score: score.strokes, putts: score.putts)
        }

        var highlights: [String] = []
        if privacy.includeCoachingNotes, let coaching {
            highlights.append(contentsOf: coaching.actionItems)
            for strength in coaching.strengths.prefix(2) {
                highlights.append("Strength: \(strength.title)")
            }
        }

        return ExportableRoundSummary(
            courseName: round.courseName,
            date: round.date.formatted(date: .long, time: .omitted),
            totalScore: round.totalStrokes,
            relativeToPar: round.scoreRelativeToPar,
            totalPutts: round.totalPutts,
            fairwaysHit: "\(round.fairwaysHit)/\(round.fairwaysPossible)",
            gir: "\(round.girsHit)/\(round.holeScores.count)",
            penalties: round.holeScores.reduce(0) { $0 + $1.penalties },
            holeScores: holeData,
            coachingHighlights: highlights,
            locationPrivacyNote: privacy.hideExactLocation ? "Location detail was excluded from this export." : nil
        )
    }

    static func buildClubExports(summaries: [ClubSummary]) -> [ExportableClubSummary] {
        summaries.map { club in
            ExportableClubSummary(
                clubName: club.clubName,
                averageDistance: Int(club.averageDistance),
                medianDistance: Int(club.medianDistance),
                sampleSize: club.sampleSize,
                consistency: club.consistencyRating,
                confidence: club.confidence.rawValue
            )
        }
    }

    static func buildStatsExport(profile: UserProfile, summary: AnalyticsSummary, roundCount: Int) -> ExportableStatsSnapshot {
        ExportableStatsSnapshot(
            playerName: profile.playerName,
            handicapEstimate: profile.handicapEstimate,
            roundsPlayed: roundCount,
            averageScore: summary.averageScore,
            fairwayPct: summary.fairwayPct,
            girPct: summary.girPct,
            puttsPerRound: summary.puttsPerRound,
            bestScore: summary.bestRoundScore,
            generatedDate: Date().formatted(date: .long, time: .shortened)
        )
    }

    private static func padded(_ text: String, to width: Int) -> String {
        let padding = max(0, width - text.count)
        return text + String(repeating: " ", count: padding)
    }
}
